### Create order
POST http://127.0.0.1:8080/order/create/
Content-Type: application/json

{
  "debug": {
    "mode": "stub",
    "stub": "success"
  },
  "requestType": "OrderCreate",
  "requestId": "34234",
  "pair": {
    "first": "BTC",
    "second": "USD"
  },
  "quantity": 1.0,
  "price": 100.0,
  "orderType": "buy",
  "userId": "user_123"
}

### Read order
POST http://127.0.0.1:8080/order/read/
Content-Type: application/json

{
  "debug": {
    "stub": "success",
    "mode": "stub"
  },
  "requestType": "OrderRead",
  "requestId": "34234",
  "filter": null
}

### Read order
POST http://127.0.0.1:8080/order/read/
Content-Type: application/json

{
  "debug": {
    "stub": "success",
    "mode": "stub"
  },
  "requestType": "OrderRead",
  "requestId": "34234",
  "filter": {
    "filterType": "byType",
    "type": "buy"
  }
}

### Read order no stub
POST http://127.0.0.1:8080/order/read/
Content-Type: application/json

{
  "requestType": "OrderRead",
  "requestId": "34234",
  "filter": {
    "filterType": "byState",
    "state": "active"
  }
}

### Detele order
POST http://127.0.0.1:8080/order/delete/
Content-Type: application/json

{
  "debug": {
    "stub": "success",
    "mode": "stub"
  },
  "requestType": "OrderDelete",
  "requestId": "34234",
  "orderId": "123456"
}
