### Create order
POST http://127.0.0.1:8080/order/create/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJ1c2VycyIsImlzcyI6IkNyeXB0b0V4Y2hhbmdlIiwiZ3JvdXBzIjpbIkFETUlOIl0sImlkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMTExIiwiZXhwIjoyMDgyNzU4NDAwfQ.xEXlcXVVXcQUYMN4ICqldxvPRrxaVAtXn1ywwy62vsM

{
  "requestType": "OrderCreate",
  "requestId": "34234",
  "pair": {
    "first": "ETH",
    "second": "USD"
  },
  "quantity": 2.0,
  "price": 150.0,
  "orderType": "buy"
}

### Read order
POST http://127.0.0.1:8080/order/read/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJ1c2VycyIsImlzcyI6IkNyeXB0b0V4Y2hhbmdlIiwiZ3JvdXBzIjpbIkFETUlOIl0sImlkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMTExIiwiZXhwIjoyMDgyNzU4NDAwfQ.xEXlcXVVXcQUYMN4ICqldxvPRrxaVAtXn1ywwy62vsM

{
  "requestType": "OrderRead",
  "requestId": "34234",
  "filter": null
}

### Read order with filter
POST http://127.0.0.1:8080/order/read/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJ1c2VycyIsImlzcyI6IkNyeXB0b0V4Y2hhbmdlIiwiZ3JvdXBzIjpbIkFETUlOIl0sImlkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMTExIiwiZXhwIjoyMDgyNzU4NDAwfQ.xEXlcXVVXcQUYMN4ICqldxvPRrxaVAtXn1ywwy62vsM

{
  "requestType": "OrderRead",
  "requestId": "34234",
  "filter": {
    "filterType": "byType",
    "type": "buy"
  }
}

### Detele order
POST http://127.0.0.1:8080/order/delete/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJ1c2VycyIsImlzcyI6IkNyeXB0b0V4Y2hhbmdlIiwiZ3JvdXBzIjpbIkFETUlOIl0sImlkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMTExIiwiZXhwIjoyMDgyNzU4NDAwfQ.xEXlcXVVXcQUYMN4ICqldxvPRrxaVAtXn1ywwy62vsM

{
  "requestType": "OrderDelete",
  "requestId": "34234",
  "orderId": "b1e5972a-dfc7-4587-9bd6-184360a2662e"
}
